In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('IVH_ND_Filters.xlsx')

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


In [ ]:
df = df[['subject_id','Msmt #','probe', 'Filters Used', 'Notes']]

In [ ]:
spot_df = df[(df['probe']=='NB5')]

In [ ]:
spot_df

subject_id          Msmt # probe                     Filters Used  \
8         B125             NaN   NB5  (S1): CAL1034: 0.2 CAL2127: 0.2   
9         B095             NaN   NB5  (S1): CAL1034: 0.1 CAL2127: 0.2   
10        B128  No measurement   NB5    (S1): CAL1034: -8 CAL2127: -8   
11        B128             2.0   NB5  (S1): CAL1034: 0.1 CAL2127: 0.2   
12        B110            15.0   NB5         (S1): CAL1034:  CAL2127:   
..         ...             ...   ...                              ...   
944       A002             9.0   NB5                              NaN   
951       A001             6.0   NB5                              NaN   
953       A001             5.0   NB5                              NaN   
956       A001             4.0   NB5                              NaN   
964       A001             1.0   NB5                              NaN   

                                                 Notes  
8    general: \nCALIB_1 (400,504,562,608): 0.2 ND\n...  
9    general: \nCALIB_1 (413,494,561,605): ND 0.1\n...  
10        general: \nRF_1 (398,466,518,529): disregard  
11   general: patient extremely fussy so measuremen...  
12   general: \nCALIB_1 (389,475,545,589): No Filte...  
..                                                 ...  
944      DCS belta is around 1.6. need to look at data  
951                                               None  
953  pma 40 wks \nbaby is not happy camper. we only...  
956                               pma 39 wks\nroom air  
964  baby is on high frequency jet ventilator\nbeds...  

[156 rows x 5 columns]

In [ ]:
filters_used = (spot_df['Filters Used']).to_list()

In [ ]:
""""
# Linear Iteration
filter_info = filters_used[6]
i = 0
info = ''
while i < len(filter_info):
    info = info + filter_info[i]
    i = i+1
    print('1st')
    print('')
    print(info)
    print('')
    #Once S1 is in info we start looking for the different filters

    if 'S1' in info:
        print('S1 in info')
        print('')
        print(info)
        filters_copy = filters.copy()
        info = ''
        i = i + 1
        info = info + filter_info[i]

        #while we haven't reach the S2 measurments we will look into the first session filters
        while 'S2' not in info and i < len(filter_info):
            print(info)
            print('')
            if 'CAL' in info and len(info) > 6 :
                print('CAL in info and len(info) > 6')
                print('')
                print(info)
                print('')

                for index, fil in enumerate(filters_copy):
                    if fil in info: 
                        filter_found = True
                        print(fil) 
                        current_filter = fil
                        del filters_copy[index]
                        break
                    else: filter_found = False;  print('F')
                print(info + '  Hola')
                if not filter_found: 
                    print('not filter_found')
                    i = i +1; info = info + filter_info[i] 


                while filter_found: 
                    print('while')
                    print(filter_found)
                    if '.' in info:
                        print('. found')
                        value = filter_info[i-1:i+2]
                        array = filters_dict[fil] 
                        array = np.append(array,float(value))
                        filters_dict[fil] = array
                        info = ''
                        i = i+1; info = info + filter_info[i]
                        filter_found = False
                        print(filter_found)

                    else: 
                        if any(word.lower() in info.lower() for word in ['none', 'na', 'notes']):
                            print('info '+ info)
                            info = ''
                            filter_found = False
                            print(filter_found)

                        print('not found yet')
                        print(filter_found)
                        print(info)
                        i = i+1; info = info + filter_info[i] 

            else: 
                #print(i)
                i = i+1; 
                try:
                    info = info +filter_info[i] 
                except: break

"""

'"\n# Linear Iteration\nfilter_info = filters_used[6]\ni = 0\ninfo = \'\'\nwhile i < len(filter_info):\n    info = info + filter_info[i]\n    i = i+1\n    print(\'1st\')\n    print(\'\')\n    print(info)\n    print(\'\')\n    #Once S1 is in info we start looking for the different filters\n\n    if \'S1\' in info:\n        print(\'S1 in info\')\n        print(\'\')\n        print(info)\n        filters_copy = filters.copy()\n        info = \'\'\n        i = i + 1\n        info = info + filter_info[i]\n\n        #while we haven\'t reach the S2 measurments we will look into the first session filters\n        while \'S2\' not in info and i < len(filter_info):\n            print(info)\n            print(\'\')\n            if \'CAL\' in info and len(info) > 6 :\n                print(\'CAL in info and len(info) > 6\')\n                print(\'\')\n                print(info)\n                print(\'\')\n\n                for index, fil in enumerate(filters_copy):\n                    if fil

In [ ]:

def changing_limiting_values(counter,info,value_1,value_2,string_value,filters_to_find,ses_dicts,note_dict,filt_idx):
    if value_1 in info:
        #print(value_1 + ' in info')
        #print('')
        #print(info)
        filters_copy = filters_to_find.copy()
        info = ''
        counter = counter + 1
        info = info + string_value[counter]

        #while we haven't reach the S2 measurments we will look into the first session filters
        while value_2 not in info and counter < len(string_value):
            #print(info)
            #print('')
            if 'CAL' in info and len(info) > 6 :
                #print('CAL in info and len(info) > 6')
                #print('')
                #print(info)
                #print('')

                for index, fil in enumerate(filters_copy):
                    if fil in info: 
                        filter_found = True
                        #print(fil) 
                        del filters_copy[index]
                        break
                    else: filter_found = False;  
                
                if not filter_found: 
                    #print('not filter_found')
                    counter = counter +1; 
                    try: info = info + string_value[counter] 
                    except: break


                while filter_found: 
                    if '.' in info:
                        value = string_value[counter-1:counter+2]
                        array = ses_dicts[value_1][fil] 
                        array = np.append(array,float(value))
                        ses_dicts[value_1][fil]  = array
                        info = ''
                        counter = counter+1; info = info + string_value[counter]
                        filter_found = False

                    else: 
                        if any(word.lower() in info.lower() for word in ['none', 'na', 'notes', 'no filter']):
                            if 'notes' in info: 
                                note_array = note_dict[value_1][fil] 
                                note_array = np.append(note_array, filt_idx)
                                note_dict[value_1][fil] = note_array
                            info = ''
                            filter_found = False

                        counter = counter+1; 
                        try: info = info + string_value[counter] 
                        except: break
                        

            else: 
                #print(i)
                counter = counter+1; 
                try:
                    info = info +string_value[counter] 
                except: break
    return ses_dicts, note_dict, counter, info

In [ ]:
def find_values_between_strvalues(string_value_to_analyze,limiting_str_values,values_to_find,s_dicts,nots_dict,filter_index):
     
    i = 0
    info = ''
    lim_value_counter = 0
    time_to_break = False

    while i < len(string_value_to_analyze): 
        info = info + string_value_to_analyze[i]
        i = i+1
        #print('1st')
        #print('')
        #print('info ' +info)
        #print('')
        #print(limiting_str_values[lim_value_counter])
        
        if limiting_str_values[lim_value_counter] in info:
            if info in string_value_to_analyze:
                lim_value_1 = limiting_str_values[lim_value_counter]
                #print(lim_value_counter)
                #print(len(limiting_str_values) - 1 )
                if lim_value_counter == len(limiting_str_values) - 1 :
                    #print('Entered 2nd if')
                    lim_value_2= 'shgkjsdhag'; time_to_break = True

                else: lim_value_2 = limiting_str_values[lim_value_counter + 1]

            s_dicts,nots_dict,i,info2 = changing_limiting_values(i,info,lim_value_1,lim_value_2,string_value_to_analyze,values_to_find,s_dicts,nots_dict,filter_index)
            lim_value_counter = lim_value_counter + 1
            info = info2
            i = i+1
        
        if time_to_break:
            break
        #print('while info: ' +info)
    
    return s_dicts, nots_dict

In [ ]:
#filter_info = filters_used[8]
i = 0
info = ''
filters_dict = {}
filters_dict['1034']=[]; filters_dict['1084'] = []; filters_dict['2127'] =[];
sesion_dicts = {}
sesion_dicts['S1'] = filters_dict.copy();sesion_dicts['S2'] = filters_dict.copy(); sesion_dicts['S3'] = filters_dict.copy() 
notes_dict = {}
notes_dict['S1'] = filters_dict.copy();notes_dict['S2'] = filters_dict.copy(); notes_dict['S3'] = filters_dict.copy() 

filters = ['1034', '1084', '2127']
exceptions = []
no_session = []
discarded = []
# A function to find values between string values in this case between 'S1' and 'S2'
limiting_str_values = ['S1','S2', 'S3']

for f_index,filter_ in enumerate(filters_used):
    
    limiting_str_values = ['S1','S2', 'S3']
  
    if 'nan' == str(filter_): 
        discarded = np.append(discarded,f_index)
        #print(str(f_index)+ ' discarded')

    elif '+' in filter_:
        exceptions = np.append(exceptions,f_index)
        #print(str(f_index)+ ' is an exception +')

    
    elif filter_== 'none':
        #print(str(f_index) + ' discarded')
        discarded = np.append(discarded,f_index)


   
        

    elif limiting_str_values[0] in filter_:

        for idx, lim_value, in reversed(list(enumerate(limiting_str_values))):
            if lim_value not in filter_:
                del limiting_str_values[idx]
            else: break

        sesion_dicts,notes_dict = find_values_between_strvalues(filter_,limiting_str_values,filters,sesion_dicts,notes_dict,f_index)
    
    else: 
        #print(str(f_index) + ' is an exception --> no session'); 
        no_session = np.append(no_session,f_index)

In [ ]:
filters_used[123]

'0.1 on 2127'

In [ ]:
sesion_dicts

{'S1': {'1034': array([0.2, 0.1, 0.1, 0.1, 0.5, 0.1, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.3,
         0.2, 0.2, 0.3, 0.3, 0.1, 0.2, 0.1, 0.1, 0.4, 0.2, 0.1, 0.1, 0.2,
         0.1, 0.2, 0.2, 0.3, 0.1, 0.1, 0.1, 0.4, 0.3, 0.2, 0.2, 0.1, 0.1,
         0.1, 0.2, 0.1, 0.1, 0.2, 0.1, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
         0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1,
         0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
         0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
         0.1]),
  '1084': array([0.1, 0.2, 0.1, 0.1, 0.2, 0.2, 0.1, 0.2]),
  '2127': array([0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 0.2, 0.6, 0.2, 0.3, 0.3, 0.2, 0.2,
         0.2, 0.2, 0.6, 0.3, 0.3, 0.4, 0.3, 0.1, 0.3, 0.3, 0.1, 0.2, 0.5,
         0.3, 0.1, 0.1, 0.3, 0.2, 0.1, 0.3, 0.2, 0.3, 0.1, 0.2, 0.1, 0.4,
         0.5, 0.2, 0.3, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.2,
         0.2, 0.2, 0.3, 0.2, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3,
         0.2, 0

In [ ]:
notes_dict

{'S1': {'1034': array([ 28.,  48.,  55.,  62.,  67.,  85., 115., 116.]),
  '1084': array([114.]),
  '2127': array([ 28.,  48.,  55.,  62.,  67.,  85., 115., 116.])},
 'S2': {'1034': array([ 48.,  55.,  62.,  67., 115., 116.]),
  '1084': [],
  '2127': array([ 48.,  55.,  62.,  67., 115., 116.])},
 'S3': {'1034': array([ 48., 116.]), '1084': [], '2127': array([ 48., 116.])}}

In [ ]:
exceptions

array([57., 74., 78., 79., 86.])

In [ ]:
no_session

array([123., 124., 125., 126., 127., 128., 129., 130., 131., 132., 133.,
       135., 137., 138., 139., 141.])

## MANUAL PROCESSING

In [ ]:
for exception in exceptions: 
    print(filters_used[int(exception)])

(S1): CAL1034: 0.2 CAL2127: 0.2 (S2): CAL1034: 0.3+0.1 CAL2127: 0.6
(S1): CAL1034: 0.3 ND CAL2127: 0.1 + 0.3 ND (S2): CAL1034: 0.5 ND CAL2127: 0.5 ND + 0.1 ND
(S1): CAL1034: 0.1 + 0.5 ND CAL2127: 0.7 ND
(S1): CAL1034: 0.3 + 0.1 CAL2127: 0.5
(S1): CAL1034: 0.2 ND + 0.3 ND CAL2127: 0.6 ND + 0.1 ND


In [ ]:
S1_1034 = sesion_dicts['S1']['1034']
S1_2127 = sesion_dicts['S1']['2127']
S2_1034 = sesion_dicts['S2']['1034']
S2_2127 = sesion_dicts['S2']['2127']

In [ ]:
S1_1034 = np.append(S1_1034,[0.2,0.3,0.6,0.4,0.5])
S1_2127 = np.append(S1_2127,[0.2,0.4,0.7,0.5,0.7])
S2_1034 = np.append(S2_1034,[0.4,0.5])
S2_2127 = np.append(S2_2127,[0.6,0.6])

sesion_dicts['S1']['1034'] = S1_1034
sesion_dicts['S1']['2127'] = S1_2127
sesion_dicts['S2']['1034'] = S2_1034
sesion_dicts['S2']['2127'] = S2_2127


In [ ]:
notes_dict['S1']['1034']

array([ 28.,  48.,  55.,  62.,  67.,  85., 115., 116.])

In [ ]:
notes_dict['S1']['2127']

array([ 28.,  48.,  55.,  62.,  67.,  85., 115., 116.])

In [114]:
notes_list = spot_df['Notes'].to_list()
notes_list[48]

'general: Bed: 901B\nCAL1034_1 (581,712,718,713): 0.8 ND\nCAL2127_1 (581,712,718,713): 1.0 ND\nLP_1 (581,712,718,713): Slight room light on D\nLP_2 (581,712,718,713): Sats, disregard\nLP_3 (581,712,718,713): Slight room light on B, C, and D\nLP_4 (581,712,718,713): Slight room light on B, C, and D\nLP_5 (581,712,718,713): Slight room light on B, C, and D. Slight movement and sats in last 10 seconds\nCAL1034_1 (403,458,504,548): 0.1 ND\nCAL2127_1 (403,458,504,548): 0.1 ND\nRF_1 (403,458,504,548): Good\nRF_2 (403,458,504,548): Good\nRF_3 (403,458,504,548): Good\nRF_4 (403,458,504,548): Good\nRF_5 (403,458,504,548): slight movement in last 2 seconds\nRF_6 (403,458,504,548): Good\nLF_1 (403,458,504,548): Good\nLF_2 (403,458,504,548): Good\nLF_3 (403,458,504,548): Movement at 22, 16, and last 2 (Disregard)\nLF_4 (403,458,504,548): Good\nLF_5 (403,458,504,548): Good\nLF_6 (403,458,504,548): Good\nLF_7 (403,458,504,548): Good\nCAL1034_1 (431,518,584,622): 0.2 ND\nCAL2127_1 (431,518,584,622): 

In [108]:
S1_1034 = sesion_dicts['S1']['1034']
S1_2127 = sesion_dicts['S1']['2127']

In [ ]:
S1_1034 = np.append(S1_1034,[0.1,])
S1_2127 = np.append(S1_2127,[0.2])

In [ ]:
# Questions for Jason, is a sum just a sum or does it mean anything else

In [107]:
filters_used[28]

'(S1): CAL1034: see notes CAL2127: see notes'